name: CI/CD

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Hadolint test
      run: |
        cd app
        wget https://github.com/hadolint/hadolint/releases/download/v1.17.5/hadolint-Linux-x86_64 -O hadolint
        chmod +x hadolint
        ./hadolint Dockerfile